pipeline:
  greenkeeper_update_lockfile:
    image: plugins/greenkeeper
    pull: true
    update: true
  build:
    image: node
    pull: true
    commands:
      - npm install
  lint:
    image: node
    commands:
      - npm run lint
  test:
    image: node
    commands:
      - npm test
  greenkeeper_lockfile_upload:
    image: plugins/greenkeeper
    upload: true
    secrets: 
      - source: gh_token
        target: gk_token
  publish:
    image: node
    commands:
      - git fetch --tags --quiet origin
      - npx semantic-release
    secrets: [ gh_token, npm_token ]
    when:
      branch: master
      event: [ push ]
