pipeline:
  build:
    image: node:10
    pull: true
    commands:
      - npm install

  lint:
    image: node:10
    commands:
      - npm run lint

#  test:
#    image: node:10
#    commands:
#      - npm test

  publish:
    image: node:10
    commands:
      - git fetch --tags --quiet origin
      - npx semantic-release@17.4.7
    secrets: [ gh_token, npm_token ]
    when:
      branch: master
      event: [ push ]
